export const LOAD_ITEMS = "LOAD_ITEMS";
export const ITEM_LOAD_FAILED = "ITEM_LOAD_FAILED";
export const SELECTED_ITEM = "SELECTED_ITEM";

export const LOAD_COMMENTS = "LOAD_COMMENTS";
export const COMMENT_LOAD_FAILED = "COMMENT_LOAD_FAILED";

export const LOAD_CATEGORIES = "LOAD_CATEGORIES";
export const CATEGORY_LOAD_FAILED = "CATEGORY_LOAD_FAILED";
export const SELECTED_CATEGORY = "SELECTED_CATEGORY";

export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAILED = "AUTH_FAILED";
export const AUTH_LOADING = "AUTH_LOADING";
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const COMMENT_SUBMIT_FAILED = "COMMENT_SUBMIT_FAILED";
export const COMMENT_SUBMIT_LOADING = "COMMENT_SUBMIT_LOADING";
export const COMMENT_SUBMIT_SUCCESS = "COMMENT_SUBMIT_SUCCESS";


